version: "3.8"
services:
  mongo:
    container_name: filmes-mongo
    image: filmes-mongo:1.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - filmes-network

  mongo-express:
    container_name: filmes-mongo-express
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpass@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_BASICAUTH_USERNAME: willian
      ME_CONFIG_BASICAUTH_PASSWORD: willianpass
    ports:
      - "8001:8081"
    networks:
      - filmes-network

  movie-api:
    container_name: movie-api
    image: movie-docker:1.1
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:rootpass@mongo:27017/
    ports:
      - "3030:3030"
    networks:
      - filmes-network

networks:
  filmes-network:
    driver: bridge
